// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebAPI.Data;

namespace WebAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211210192356_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WedAPI.Buyer", b =>
                {
                    b.Property<int>("BuyerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Payment")
                        .HasColumnType("text");

                    b.Property<int>("ShoesID")
                        .HasColumnType("integer");

                    b.Property<string>("part")
                        .HasColumnType("text");

                    b.Property<int?>("shoesShopShoesID")
                        .HasColumnType("integer");

                    b.HasKey("BuyerID");

                    b.HasIndex("shoesShopShoesID");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("WedAPI.ShoesShop", b =>
                {
                    b.Property<int>("ShoesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Mark")
                        .HasColumnType("text");

                    b.Property<string>("price")
                        .HasColumnType("text");

                    b.HasKey("ShoesID");

                    b.ToTable("ShoesShops");
                });

            modelBuilder.Entity("WedAPI.Buyer", b =>
                {
                    b.HasOne("WedAPI.ShoesShop", "shoesShop")
                        .WithMany()
                        .HasForeignKey("shoesShopShoesID");

                    b.Navigation("shoesShop");
                });
#pragma warning restore 612, 618
        }
    }
}
